# @package _global_

# specify here default sim configuration
defaults:
  - _self_

  - mode: default.yaml

# path to original working directory
# hydra hijacks working directory by changing it to the current log directory,
# so it's useful to have this path as a special variable
# https://hydra.cc/docs/next/tutorials/basic/running_your_app/working_directory
work_dir: ${hydra:runtime.cwd}

# path to folder with data
data_dir: data
upload: false

output_path: 2D_diff-react_NA_NA

# name of the run, accessed by loggers
case: ns_hit

sim:
  n: 512
  L: 2
  Re: 1000
  dim: 2
  T: 20
  dt: .01
  rx: 8
  rt: 1
  seed: 123
  case_num: 1       # number of simulations to perform
  warm_up: 200      # warm up step for simulation
  patience: 5       # patience for NaN simulation
  writeInterval: 2
  
plot:
  t_idx: 1.0        # Fraction of the final time step idx to be plotted
  dim: 2            # Spatial dimension
  channel_idx: 0    # Index of the variable to be plotted

train:
  lr: 0.01
  sgs: filter
  # sgs: correction
  kernel_size: 3
  # input: u
  input: global
  buffer_size: 10
  epochs_global: 400
  decay_global: 100 # number of epochs to decay the learning rate
  batch_size_global: 200
  epochs_local: 1
  decay_local: 5
  batch_size_local: 100000
  save: 100
  vae:
    latents: 128

dagger:
  lr: 0.01
  epochs: 10
  inner_epochs: 10
  beta: 0.0

tr:
  lambda_mols: 10

test:
  model: alos
  solver: CN # CN, RK4

dataverse:
  lib_name: NA
  dataset_id: NA
  metadatablocks:
    citation:
      author:
        - name: Jiaxi Zhao
          affiliation: National University of Singapore
          identifier_scheme: ORCID
          identifier: 0009-0007-2110-6006
      description:
        - text: 2D diffusion-reaction dataset
          date: 2024
      contact:
        - name: Jiaxi Zhao
          affiliation: National University of Singapore
          email: jiaxi.zhao@u.nus.edu
      title: 2D diffusion-reaction dataset
      subject:
        - computer_and__information__science
        - physics
    process:
      processing_methods:
        - name: FVM
          description: Finite Volume Method is a spatial discretization method to calculate spatial derivative in a Partial Differential Equation. It integrates the fluxes at all discrete cell boundaries so that it ensures conservation.
          parameters: cell length, cell width
        - name: RK45
          description: Explicit Runge-Kutta method of order 5(4) is a time integration method to solve the temporal derivative in a Partial Differential Equation. It is an adaptive time integration scheme to ensure better accuracy and computation efficiency.
          parameters: time step size, total time, error tolerance
      method_parameters:
        - name: cell length
          symbol: dx
          unit: m
          value: 0.015625
        - name: cell width
          symbol: dy
          unit: m
          value: 0.015625
        - name: time step size
          symbol: dt
          unit: s
          value: 0.05
        - name: total time
          symbol: t
          unit: s
          value: 5
        - name: error tolerance
          symbol: \epsilon
          unit: "-"
          value: 1e-6
    engMeta: {}
    codeMeta: {}